### ISSUE TITLE
Not compatible with proftpd v1.3.6

### ISSUE THREAD

**Issue by Vincent--** [Castaglia/proftpd-mod_rename#4]
Trying to compile mod_rename on proftpd v1.3.6:
```
mod_rename.c: In function ‘rename_fixup_path’:
mod_rename.c:77:12: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
     prefix = sreplace(tmp_pool, tmp, "~", session.user, NULL);
            ^
mod_rename.c:85:12: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
     suffix = sreplace(tmp_pool, tmp, "~", session.user, NULL);
            ^
mod_rename.c:186:22: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
           tmp_prefix = sreplace(tmp_pool, prefix, "#", prefixbuf, NULL);
                      ^
mod_rename.c:195:22: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
           tmp_suffix = sreplace(tmp_pool, suffix, "#", suffixbuf, NULL);
                      ^
mod_rename.c: In function ‘set_renamelog’:
mod_rename.c:695:7: warning: dereferencing ‘void *’ pointer [enabled by default]
       *(cmd->argv[1]) != '/') {
       ^
mod_rename.c:695:7: error: void value not ignored as it ought to be
make[1]: *** [mod_rename.o] Error 1
make[1]: Leaving directory `/usr/local/src/proftpd/proftpd-1.3.6/modules'
make: *** [modules] Error 2
```

Compile options used:
```
./configure \
            --prefix=/usr \
            --mandir=/usr/share/man \
            --sysconfdir=/etc/proftpd \
            --localstatedir=/var/run \
            --libexecdir=/usr/lib/proftpd \
            --enable-sendfile \
            --enable-facl \
            --enable-dso \
            --enable-autoshadow \
            --enable-ctrls \
            --enable-openssl \
            --with-modules=mod_rename:mod_sql:mod_sql_passwd:mod_sql_mysql:mod_sftp:mod_sftp_sql \
            --enable-nls \
            --build x86_64-linux-gnu build_alias=x86_64-linux-gnu CFLAGS=-O2
```

(this was working ok on 1.3.5x series)

**Comment by Castaglia** [comment]
Which version of `gcc` are you using?  I suspect that that is also involved; the [Travis CI job](https://travis-ci.org/Castaglia/proftpd-mod_rename/jobs/201924131) for `mod_rename` shows the above _warnings_, but not as _errors_.

**Comment by Castaglia** [comment]
I also wondering which version of the `mod_rename` source you are using; the above build error:

    mod_rename.c:695:7: error: void value not ignored as it ought to be

does not occur in the current source code in GitHub, since that `path` variable is a `char *`; see:

  https://github.com/Castaglia/proftpd-mod_rename/blob/master/mod_rename.c#L694

Is it possible, then, that part of this issue may be old/stale version of the `mod_rename.c` file being used?

**Comment by Castaglia** [comment]
The cast warnings are fixed in the current master branch; the build error had already been fixed there.

**Comment by Vincent--** [comment]
wow, that was a fast fix 👍 

I was using v0.4 with this version of gcc:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
```

Just tested with last version of master and it works perfectly. Thank you for the advice and the fix, I completely forgot to check that.

Could you eventually tag a new release? As I use that on production, I'd rather use a version number than master or a commit number...
Thanking you in advance.

**Comment by Castaglia** [comment]
Done; see:
  https://github.com/Castaglia/proftpd-mod_rename/releases/tag/v0.4.1

**Comment by Vincent--** [comment]
Thank you 👍
